<?php

return [
    "name" => "vacancyreaction",
    "title" => "Reacties",
    "description" => "Vacatures reacties module",
    "module_name" => [
        "single" => "Reactie",
        "multiple" => "Reacties"
    ],
    "tabtitle" => "firstname",
    "type" => "module",
    "active" => true,
    "locale" => "nl",
    "data" => [],
    "sort" => 999,
    "route" => null,
    "url" => null,
    "icon" => null,
    "rights" => null,
    "tab_title" => "firstname",
    "ereg" => [
        "tables" => [
            'vacancyreactions' => [
                'variable' => 'vacancyreaction',
                "select" =>
                [
                    'company',
                    'title',
                    'sex',
                    'firstname',
                    'middlename',
                    'lastname',
                    'email',
                    'phone',
                    'address',
                    'address_nr',
                    'zipcode',
                    'city',
                    'country',
                    'birthdate',
                    'subject',
                    'comment',
                    'internal_contact',
                    'ip',
                    'option_1',
                    'option_2',
                    'option_3',
                    'option_4',
                    'option_5',
                    'option_6',
                ]
            ],
        ]
    ],
    "settings" => [
        "VACANCYREACTION_EMAIL_RECEIVERS" => [
            "title" => "Email ontvanger(s)",
            "type" => "email_receivers",
            "default" => env('MAIL_TO_ADDRESS'),
        ],
        "VACANCYREACTION_EMAIL_SUBJECT" => [
            "title" => "Email onderwerp",
            "type" => "text",
            "default" => 'Bedankt voor uw reactie',
        ],
        "VACANCYREACTION_EMAIL_WEBMASTER_SUBJECT" => [
            "title" => "Email onderwerp webmaster",
            "type" => "",
            "default" => 'Er is een reactie via de website',
        ],
        "VACANCYREACTION_EMAIL" => [
            "title" => "Email onderwerp",
            "type" => "editor",
            "default" => '',
        ],
        "VACANCYREACTION_EMAIL_WEBMASTER" => [
            "title" => "Email onderwerp webmaster",
            "type" => "",
            "default" => '',
        ],
    ],
    "fields" => [
        "uploads" => [
            "active" => false,
            "type" => "",
            "title" => "Uploads",
            "read" => false
        ],
        "locale" => [
            "active" => false,
            "type" => "text",
            "title" => "Taal",
            "read" => true
        ],
        "company_id" => [
            "active" => false,
            "type" => "integer",
            "title" => "Bedrijfs-ID",
            "read" => true,
            "required" => false,
            "edit" => false,
        ],
        "host" => [
            "active" => false,
            "type" => "text",
            "title" => "Host",
            "read" => true,
            "required" => false,
            "edit" => false,
        ],
        "pid" => [
            "active" => false,
            "type" => "integer",
            "title" => "Parent ID",
            "read" => true,
            "required" => false,
            "edit" => false,
        ],

        "active" => [
            "active" => false,
            "type" => "boolean",
            "title" => "Actief",
            "read" => true,
            "required" => true,
            "edit" => false,
        ],
        "sort" => [
            "active" => false,
            "type" => "integer",
            "title" => "Sorteer",
            "read" => true,
            "required" => true,
            "edit" => false,
        ],
        "company" => [
            "active" => false,
            "type" => "text",
            "title" => "Bedrijf",
            "read" => true,
            "required" => false,
            "edit" => false,
        ],
        "title" => [
            "active" => false,
            "type" => "text",
            "title" => "Titel",
            "read" => true,
            "required" => false,
            "edit" => false,
        ],
        "sex" => [
            "active" => false,
            "type" => "text",
            "title" => "Geslacht",
            "read" => true,
            "required" => false,
            "edit" => false,
        ],
        "firstname" => [
            "active" => true,
            "type" => "text",
            "title" => "Voornaam",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "middlename" => [
            "active" => false,
            "type" => "text",
            "title" => "Tussenvoegsel",
            "read" => true,
            "required" => false,
            "edit" => false,
        ],
        "lastname" => [
            "active" => true,
            "type" => "text",
            "title" => "Achternaam",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "email" => [
            "active" => true,
            "type" => "text",
            "title" => "E-mail",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "phone" => [
            "active" => true,
            "type" => "text",
            "title" => "Telefoon",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "address" => [
            "active" => true,
            "type" => "text",
            "title" => "Adres",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "address_nr" => [
            "active" => false,
            "type" => "text",
            "title" => "Huisnummer",
            "read" => true,
            "required" => false,
            "edit" => false,
        ],
        "zipcode" => [
            "active" => true,
            "type" => "text",
            "title" => "Postcode",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "city" => [
            "active" => true,
            "type" => "text",
            "title" => "Stad",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "country" => [
            "active" => true,
            "type" => "text",
            "title" => "Land",
            "read" => true,
            "required" => false,
            "edit" => true,
        ],
        "birthdate" => [
            "active" => false,
            "type" => "date",
            "title" => "Geboortedatum",
            "read" => true,
            "required" => false,
            "edit" => false,
        ],
        "subject" => [
            "active" => false,
            "type" => "text",
            "title" => "Onderwerp",
            "read" => true,
            "required" => false,
            "edit" => false,
        ],
        "comment" => [
            "active" => false,
            "type" => "textarea",
            "title" => "Opmerking",
            "read" => true,
            "required" => false,
            "edit" => false,
        ],
        "internal_contact" => [
            "active" => false,
            "type" => "text",
            "title" => "Interne Contactpersoon",
            "read" => true,
            "required" => false,
            "edit" => false,
        ],
        "ip" => [
            "active" => false,
            "type" => "text",
            "title" => "IP-adres",
            "read" => true,
            "required" => false,
            "edit" => false,
        ],
    ]
];
